<?php
add_action('acf/include_fields', function () {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group(array(
        'key' => 'group_6579f6d9c1e07',
        'title' => 'Publication fields',
        'fields' => array(
            array(
                'key' => 'field_6579f6daeebda',
                'label' => 'Is PDF?',
                'name' => 'is_pdf',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'This will make it link straight to the PDF.',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_6579f728605c3',
                'label' => 'PDF Upload',
                'name' => 'pdf_upload',
                'aria-label' => '',
                'type' => 'file',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'library' => 'uploadedTo',
                'min_size' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_6579f82c605c7',
                'label' => 'Author Firstname',
                'name' => 'author_firstname',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6579f832605c8',
                'label' => 'Author Lastname',
                'name' => 'author_lastname',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'publication',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));
});

add_action('init', function () {
    register_post_type('publication', array(
        'labels' => array(
            'name' => 'Publications',
            'singular_name' => 'Publication',
            'menu_name' => 'Publications',
            'all_items' => 'All Publications',
            'edit_item' => 'Edit Publication',
            'view_item' => 'View Publication',
            'view_items' => 'View Publications',
            'add_new_item' => 'Add New Publication',
            'new_item' => 'New Publication',
            'parent_item_colon' => 'Parent Publication:',
            'search_items' => 'Search Publications',
            'not_found' => 'No publications found',
            'not_found_in_trash' => 'No publications found in Trash',
            'archives' => 'Publication Archives',
            'attributes' => 'Publication Attributes',
            'insert_into_item' => 'Insert into publication',
            'uploaded_to_this_item' => 'Uploaded to this publication',
            'filter_items_list' => 'Filter publications list',
            'filter_by_date' => 'Filter publications by date',
            'items_list_navigation' => 'Publications list navigation',
            'items_list' => 'Publications list',
            'item_published' => 'Publication published.',
            'item_published_privately' => 'Publication published privately.',
            'item_reverted_to_draft' => 'Publication reverted to draft.',
            'item_scheduled' => 'Publication scheduled.',
            'item_updated' => 'Publication updated.',
            'item_link' => 'Publication Link',
            'item_link_description' => 'A link to a publication.',
        ),
        'public' => true,
        'show_in_rest' => true,
        'supports' => array(
            0 => 'title',
            1 => 'editor',
            2 => 'thumbnail',
        ),
        'taxonomies' => array(
            0 => 'category',
        ),
        'has_archive' => 'publications',
        'rewrite' => array(
            'feeds' => false,
        ),
        'delete_with_user' => false,
    ));
});

add_action('init', function () {
    register_taxonomy('publication_year', array(
        0 => 'publication',
    ), array(
        'labels' => array(
            'name' => 'Publication Years',
            'singular_name' => 'Publication Year',
            'menu_name' => 'Publication Year',
            'all_items' => 'All Publication Year',
            'edit_item' => 'Edit Publictaion',
            'view_item' => 'View Publictaion',
            'update_item' => 'Update Publictaion',
            'add_new_item' => 'Add New Publictaion',
            'new_item_name' => 'New Publictaion Name',
            'search_items' => 'Search Publication Year',
            'popular_items' => 'Popular Publication Year',
            'separate_items_with_commas' => 'Separate publication year with commas',
            'add_or_remove_items' => 'Add or remove publication year',
            'choose_from_most_used' => 'Choose from the most used publication year',
            'not_found' => 'No publication year found',
            'no_terms' => 'No publication year',
            'items_list_navigation' => 'Publication Year list navigation',
            'items_list' => 'Publication Year list',
            'back_to_items' => '← Go to publication year',
            'item_link' => 'Publictaion Link',
            'item_link_description' => 'A link to a publictaion',
        ),
        'public' => true,
        'show_in_menu' => true,
        'show_in_rest' => true,
    ));
});
